### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by josephting** [sean-william/X#2]

**Comment by sean-william** [comment]
Hello! Got your message in a bottle. Haha. Learning loops now

**Comment by josephting** [comment]
Pro loop no push your work to Github? 🤣

**Comment by sean-william** [comment]
haha and let the whole world laugh at it?

loopy loop haha

mylist = [1,2,3,4,5]
for items in mylist:
    print(items)

**Comment by josephting** [comment]
hahaha push only I can collaborate
or else [gitlab](https://gitlab.com) can create private repository for free lol

**Comment by sean-william** [comment]
what you wanna do with that code? that's basically it dy hahaha.

okay. Let me try getting on gitlab

**Comment by josephting** [comment]
haha nothing just in case if you need help
this will be the medium for collaboration

**Comment by sean-william** [comment]
im on gitlab already. But seems like will need to create a group or something?
host please hahaha

**Comment by josephting** [comment]
Link to a repo after you have created it? You want a group? LOL

**Comment by sean-william** [comment]
Don't know how it works haha. Guess i'll post it there when i need help then haha

**Comment by sean-william** [comment]
Just saw some PCAP python certificate thingy. You got take those?

**Comment by josephting** [comment]
No, I'm terrible in Python.
I created a group on gitlab. HAHAHA
Create a repo there if you want I guess.

**Comment by sean-william** [comment]
LOL yay this is sort of fun haha. something new?
I thought you're good at everything haha

**Comment by sean-william** [comment]
oh wait, i think need your invitation or something to get into that group?

**Comment by josephting** [comment]
Already invited.

https://gitlab.com/the-bosses/index/issues/1
